apiVersion: apps/v1
kind: Deployment
metadata:
  name: penghian-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penghian-api
  template:
    metadata:
      labels:
        app: penghian-api
    spec:
      containers:
      - name: penghian-api
        image: penghian-api:latest
        ports:
        - containerPort: 5000
